### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ColinChartier** [webappio/greenjs#1]
- [ ] README
- [ ] Favicon for docs
- [ ] Comparison pages (benchmarks?)
- [ ] Chrome builds hang
- [ ] Output doesn't get tailed while building
- [ ] Should cache built html (map input files to page)
